### ISSUE TITLE
incompatible with ghost 1.19.0

### ISSUE THREAD

**Issue by mayaa6** [minwe/qn-store#17]
```
 Error: Cannot find module '/var/lib/ghost/current/core/server/errors'
     at Function.Module._resolveFilename (module.js:469:15)
     at Function.Module._load (module.js:417:25)
     at Module.require (module.js:497:17)
     at require (internal/module.js:20:19)
     at Object.<anonymous> (/var/lib/ghost/content/adapters/storage/qn-store/index.js:33:16)
     at Module._compile (module.js:570:32)
     at Object.Module._extensions..js (module.js:579:10)
     at Module.load (module.js:487:32)
     at tryModuleLoad (module.js:446:12)
     at Function.Module._load (module.js:438:3)
     at Module.require (module.js:497:17)
     at require (internal/module.js:20:19)
     at Object.getStorage (/var/lib/ghost/versions/1.19.0/core/server/adapters/storage/index.js:32:25)
     at setupSiteApp (/var/lib/ghost/versions/1.19.0/core/server/web/site/app.js:69:73)
     at setupParentApp (/var/lib/ghost/versions/1.19.0/core/server/web/parent-app.js:54:36)
     at /var/lib/ghost/versions/1.19.0/core/server/index.js:74:48
     at tryCatcher (/var/lib/ghost/versions/1.19.0/node_modules/bluebird/js/release/util.js:16:23)
     at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/1.19.0/node_modules/bluebird/js/release/promise.js:512:31)
     at Promise._settlePromise (/var/lib/ghost/versions/1.19.0/node_modules/bluebird/js/release/promise.js:569:18)
     at Promise._settlePromise0 (/var/lib/ghost/versions/1.19.0/node_modules/bluebird/js/release/promise.js:614:10)
     at Promise._settlePromises (/var/lib/ghost/versions/1.19.0/node_modules/bluebird/js/release/promise.js:693:18)
     at Promise._fulfill (/var/lib/ghost/versions/1.19.0/node_modules/bluebird/js/release/promise.js:638:18)
```

version 1.19.0 has made big changes in file structure

**Comment by zce** [comment]
+1

**Comment by minwe** [comment]
I'll try to fix it later tonight.
