### ISSUE TITLE
incompatible with ghost 1.20.0

### ISSUE THREAD

**Issue by mayaa6** [minwe/qn-store#19]
```
 IncorrectUsageError: We have detected an error in your custom storage adapter.
     at new IncorrectUsageError (/var/lib/ghost/versions/1.20.0/node_modules/ghost-ignition/lib/errors/index.js:79:23)
     at Object.getStorage (/var/lib/ghost/versions/1.20.0/core/server/adapters/storage/index.js:42:19)
     at setupSiteApp (/var/lib/ghost/versions/1.20.0/core/server/web/site/app.js:69:73)
     at setupParentApp (/var/lib/ghost/versions/1.20.0/core/server/web/parent-app.js:54:36)
     at /var/lib/ghost/versions/1.20.0/core/server/index.js:81:48
     at tryCatcher (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/util.js:16:23)
     at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/promise.js:512:31)
     at Promise._settlePromise (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/promise.js:569:18)
     at Promise._settlePromise0 (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/promise.js:614:10)
     at Promise._settlePromises (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/promise.js:693:18)
     at Promise._fulfill (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/promise.js:638:18)
     at PromiseArray._resolve (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/promise_array.js:126:19)
     at PromiseArray._promiseFulfilled (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/promise_array.js:144:14)
     at Promise._settlePromise (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/promise.js:574:26)
     at Promise._settlePromise0 (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/promise.js:614:10)
     at Promise._settlePromises (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/promise.js:693:18)
     at Async._drainQueue (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/async.js:133:16)
     at Async._drainQueues (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/async.js:143:10)
     at Immediate.Async.drainQueues (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/async.js:17:14)
     at runCallback (timers.js:672:20)
     at tryOnImmediate (timers.js:645:5)
     at processImmediate [as _immediateCallback] (timers.js:617:5)

 Error: Cannot find module '/var/lib/ghost/current/core/server/utils'
     at Function.Module._resolveFilename (module.js:469:15)
     at Function.Module._load (module.js:417:25)
     at Module.require (module.js:497:17)
     at require (internal/module.js:20:19)
     at Object.<anonymous> (/var/lib/ghost/content/adapters/storage/qn-store/index.js:32:15)
     at Module._compile (module.js:570:32)
     at Object.Module._extensions..js (module.js:579:10)
     at Module.load (module.js:487:32)
     at tryModuleLoad (module.js:446:12)
     at Function.Module._load (module.js:438:3)
     at Module.require (module.js:497:17)
     at require (internal/module.js:20:19)
     at Object.getStorage (/var/lib/ghost/versions/1.20.0/core/server/adapters/storage/index.js:32:25)
     at setupSiteApp (/var/lib/ghost/versions/1.20.0/core/server/web/site/app.js:69:73)
     at setupParentApp (/var/lib/ghost/versions/1.20.0/core/server/web/parent-app.js:54:36)
     at /var/lib/ghost/versions/1.20.0/core/server/index.js:81:48
     at tryCatcher (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/util.js:16:23)
     at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/promise.js:512:31)
     at Promise._settlePromise (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/promise.js:569:18)
     at Promise._settlePromise0 (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/promise.js:614:10)
     at Promise._settlePromises (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/promise.js:693:18)
     at Promise._fulfill (/var/lib/ghost/versions/1.20.0/node_modules/bluebird/js/release/promise.js:638:18)
```

**Comment by minwe** [comment]
Fixed in 4.0.0: https://github.com/minwe/qn-store/releases/tag/v4.0.0

**Comment by fliaping** [comment]
版本1.22.0
```
IncorrectUsageError: We have detected an error in your custom storage adapter.
    at new IncorrectUsageError (/var/lib/ghost/versions/1.22.0/node_modules/ghost-ignition/lib/errors/index.js:79:23)
    at Object.getStorage (/var/lib/ghost/versions/1.22.0/core/server/adapters/storage/index.js:42:19)
    at setupSiteApp (/var/lib/ghost/versions/1.22.0/core/server/web/site/app.js:74:73)
    at setupParentApp (/var/lib/ghost/versions/1.22.0/core/server/web/parent-app.js:54:36)
    at /var/lib/ghost/versions/1.22.0/core/server/index.js:81:48
    at tryCatcher (/var/lib/ghost/versions/1.22.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/1.22.0/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/lib/ghost/versions/1.22.0/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/1.22.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/lib/ghost/versions/1.22.0/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/var/lib/ghost/versions/1.22.0/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/var/lib/ghost/versions/1.22.0/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/var/lib/ghost/versions/1.22.0/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/var/lib/ghost/versions/1.22.0/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/var/lib/ghost/versions/1.22.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/lib/ghost/versions/1.22.0/node_modules/bluebird/js/release/promise.js:693:18)

Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/lib/ghost/content/adapters/storage/qn-store/index.js:12:17)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.getStorage (/var/lib/ghost/versions/1.22.0/core/server/adapters/storage/index.js:32:25)
    at setupSiteApp (/var/lib/ghost/versions/1.22.0/core/server/web/site/app.js:74:73)
    at setupParentApp (/var/lib/ghost/versions/1.22.0/core/server/web/parent-app.js:54:36)
    at /var/lib/ghost/versions/1.22.0/core/server/index.js:81:48
```

**Comment by fliaping** [comment]
版本1.22.0又出现了这样的问题

我用npm安装方式，就会出现这个问题，用git方式变成找不到bluebird模块

**Comment by minwe** [comment]
@fliaping 在 qn-store 目录里面手动执行一下 npm install

我刚刚升级了 1.22.1，没遇到问题。

**Comment by fliaping** [comment]
@minwe 我用readme中的两种方法都试了，npm install也是成功的
