### ISSUE TITLE
运行时提示 Error: Cannot find module 'bluebird'

### ISSUE THREAD

**Issue by fr0der1c** [minwe/qn-store#25]
Dockerfile：
```
FROM ghost:latest

COPY ./var_lib_ghost_content/adapters/storage /var/lib/ghost/content/adapters/storage

RUN cd /var/lib/ghost/content/adapters/storage/qn-store \
	&& npm install
```

运行：
```
docker run --rm -it -v $(pwd)/config.production.json:/var/lib/ghost/config.production.json -v $(pwd)/var_lib_ghost_content:/var/lib/ghost/content -p 80:2368  --name myghost my/ghost
```

报错：
```
[2019-04-02 17:07:59] ERROR

We have detected an error in your custom storage adapter.

Error ID:
    ddfc5760-5569-11e9-b7e5-c55365f5bb95

Error Code:
    MODULE_NOT_FOUND

----------------------------------------

IncorrectUsageError: We have detected an error in your custom storage adapter.
    at new IncorrectUsageError (/var/lib/ghost/versions/2.19.1/node_modules/ghost-ignition/lib/errors/index.js:85:23)
    at Object.getStorage (/var/lib/ghost/versions/2.19.1/core/server/adapters/storage/index.js:42:19)
    at setupSiteApp (/var/lib/ghost/versions/2.19.1/core/server/web/site/app.js:64:93)
    at setupParentApp (/var/lib/ghost/versions/2.19.1/core/server/web/parent-app.js:55:36)
    at settings.init.then.then (/var/lib/ghost/versions/2.19.1/core/server/index.js:98:52)
    at tryCatcher (/var/lib/ghost/versions/2.19.1/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/var/lib/ghost/versions/2.19.1/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/var/lib/ghost/versions/2.19.1/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/var/lib/ghost/versions/2.19.1/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/var/lib/ghost/versions/2.19.1/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/var/lib/ghost/versions/2.19.1/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/var/lib/ghost/versions/2.19.1/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/var/lib/ghost/versions/2.19.1/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/var/lib/ghost/versions/2.19.1/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)

Error: Cannot find module 'bluebird'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/var/lib/ghost/content/adapters/storage/qn-store/index.js:12:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.getStorage (/var/lib/ghost/versions/2.19.1/core/server/adapters/storage/index.js:32:25)
    at setupSiteApp (/var/lib/ghost/versions/2.19.1/core/server/web/site/app.js:64:93)
    at setupParentApp (/var/lib/ghost/versions/2.19.1/core/server/web/parent-app.js:55:36)
    at settings.init.then.then (/var/lib/ghost/versions/2.19.1/core/server/index.js:98:52)
```

**Comment by fr0der1c** [comment]
找到问题了，我在启动容器的时候使用本地目录映射到把整个/var/lib/ghost/content目录，导致Dockerfile 里那一步 npm install 相当于没用（因为同目录下生成的 node_modules 被宿主上的覆盖了）
